CREATE TABLE [Faculty] (
  [ID] AUTOINCREMENT CONSTRAINT [Index_FD850532_C71E_4D7C] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [Company] VARCHAR (50),
  [Last Name] VARCHAR (50),
  [First Name] VARCHAR (50),
  [E-mail Address] VARCHAR (50),
  [Date of Birth] DATETIME ,
  [ID Number] VARCHAR (255),
  [Faculty ID] VARCHAR (255) CONSTRAINT [Faculty ID] UNIQUE ,
  [Department] VARCHAR (255),
  [Faculty Type] VARCHAR (255),
  [Office] VARCHAR (255),
  [Education Level/Degree] VARCHAR (255),
  [Focus Area] VARCHAR (255),
  [School/Program Name] VARCHAR (255),
  [Date of Hire] DATETIME ,
  [Salary] CURRENCY ,
  [Job Title] VARCHAR (50),
  [Business Phone] VARCHAR (25),
  [Home Phone] VARCHAR (25),
  [Mobile Phone] VARCHAR (25),
  [Fax Number] VARCHAR (25),
  [Address] LONGTEXT ,
  [City] VARCHAR (50),
  [State/Province] VARCHAR (50),
  [ZIP/Postal Code] VARCHAR (15),
  [Country/Region] VARCHAR (50),
  [Web Page] LONGTEXT ,
  [Notes] LONGTEXT ,
  [Attachments] VARCHAR (255),
  [Physician Name] VARCHAR (50),
  [Physician Phone Number] VARCHAR (50),
  [Allergies] VARCHAR (100),
  [Medications] VARCHAR (100),
  [Emergency Contact Name] VARCHAR (50),
  [Emergency Contact Phone 1] VARCHAR (25),
  [Emergency Contact Phone 2] VARCHAR (25),
  [Emergency Contact Relationship] VARCHAR (25)
)
